-- Data import for brightdrop table
-- Generated on 2025-05-02 18:23:17.116318
-- Contains 30 records

-- Batch 1 of 1
BEGIN;
INSERT INTO "brightdrop" ("year", "make", "model", "oem_adas_system_name", "protech_generic_system_name", "parts_code_table_value", "glass_only_pct_value", "protech_generic_system_name1", "calibration_type", "calibration_prerequisites", "calibration_prerequisites_short_hand", "service_information_hyperlink", "autel_target__part_number", "protech_target_part_number", "alignment_statement", "oe_glass_statement", "oe_glass_service_info_hyperlink", "additional_recommended_calibrations", "protech_svc_user_guide", "point_of_impact_") VALUES
('2022.0', 'Brightdrop', 'EV600', 'Adaptive Cruise Control', 'ACC %', 'On Board Calibration - Adaptive Cruise Control', 'nan', 'ACC (1)', 'PMI', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EQRlQOj5OUtDnysNkXkgyVwBrBmL_wy69SKqloDZ0cvlHQ?e=o8EvZe', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '1, 11, 12'),
('2022.0', 'Brightdrop', 'EV600', 'Forward Collision Alert', 'AEB %', 'Dynamic Calibration - Automatic Emergency Braking', 'Dynamic Calibration - Automatic Emergency Braking', 'AEB (3)', 'Dynamic', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/ERR4r7l-Yq9Ekzq7DUva1j8BKVNVFhzrVBRO9g9D86fAUw?e=4DfAPu', 'nan', 'nan', 'nan', 'The use of Aftermarket or non-Genuine parts and accessories in ADAS sensor areas including but not limited to the front bumper, front grill, below the front grill, license plate covers, headlamps, windshield, front and rear side panels, mirrors, rear camera lens, and rear bumper area is not recommended due to the potential for degradation of ADAS feature functionality.', 'https://calibercollision.sharepoint.com/:b:/g/enterpriseprojects/VehicleServiceInformation/EcITra8_imxCk2kqUV2GE8oBsf1BIuNDeVeyg44gMhlVPQ?e=nbWrJJ', 'nan', 'nan', '13'),
('2022.0', 'Brightdrop', 'EV600', 'nan', 'AHL', 'Pending', 'nan', 'AHL', 'nan', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('2022.0', 'Brightdrop', 'EV600', 'Parking Assist', 'APA', 'No Calibration Required', 'nan', 'APA', 'P&P', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EVIe9vkSBQFCsgJz41H9O-IBiZP7QTb0Thg6KptxX4baFg?e=jWuZaX', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '1, 5, 6, 7, 11, 12'),
('2022.0', 'Brightdrop', 'EV600', 'Side Obstacle Detection', 'BSW %', 'On Board Calibration - Blind Spot Warning', 'nan', 'BSW (1)', 'PMI', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '5, 6, 7'),
('2022.0', 'Brightdrop', 'EV600', 'Rear Vision Camera', 'BUC', 'On Board Calibration - Backup Camera', 'nan', 'BUC', 'PMI', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/ESCafXvpildEmSqeT4dIq0kBisO9pDFuCJEMB8ZUafSSLQ?e=AfzzSA', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '6'),
('2022.0', 'Brightdrop', 'EV600', 'Lane Departure Warning', 'LKA %', 'Dynamic Calibration - Lane Keep Assist', 'Dynamic Calibration - Lane Keep Assist', 'LKA (1)', 'Dynamic', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EaI72Kk87opOutnckbR0xg8BR5xKOAYpMIPfPoYPKprgjQ?e=E7yXW2', 'nan', 'nan', 'nan', 'The use of Aftermarket or non-Genuine parts and accessories in ADAS sensor areas including but not limited to the front bumper, front grill, below the front grill, license plate covers, headlamps, windshield, front and rear side panels, mirrors, rear camera lens, and rear bumper area is not recommended due to the potential for degradation of ADAS feature functionality.', 'https://calibercollision.sharepoint.com/:b:/g/enterpriseprojects/VehicleServiceInformation/EcITra8_imxCk2kqUV2GE8oBsf1BIuNDeVeyg44gMhlVPQ?e=nbWrJJ', 'nan', 'nan', '13'),
('2022.0', 'Brightdrop', 'EV600', 'nan', 'NV', 'Pending', 'nan', 'NV', 'nan', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('2022.0', 'Brightdrop', 'EV600', 'nan', 'SVC', 'Pending', 'nan', 'SVC', 'nan', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('2023.0', 'Brightdrop', 'Zevo 600', 'Adaptive Cruise Control', 'ACC %', 'Dynamic Calibration - Adaptive Cruise Control', 'nan', 'ACC (1)', 'Dynamic', 'Please be aware that the front bumper for this vehicle will require removal for proper Calibration.', 'Front Bumper R&I', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EUzpNeYuBAhJltNmcU-FD2cBB0KNrvVS99H57zw6rOde8Q?e=GV2CN6', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('2023.0', 'Brightdrop', 'Zevo 600', 'Forward Collision Alert', 'AEB %', 'Dynamic Calibration - Automatic Emergency Braking', 'Dynamic Calibration - Automatic Emergency Braking', 'AEB (3)', 'Dynamic', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EQngFUTMsSNPiz18rsj7aUYBdGP9Lzzre3egW61LLtrF3A?e=gIv0rn', 'nan', 'nan', 'nan', 'The use of Aftermarket or non-Genuine parts and accessories in ADAS sensor areas including but not limited to the front bumper, front grill, below the front grill, license plate covers, headlamps, windshield, front and rear side panels, mirrors, rear camera lens, and rear bumper area is not recommended due to the potential for degradation of ADAS feature functionality.', 'https://calibercollision.sharepoint.com/:b:/g/enterpriseprojects/VehicleServiceInformation/EcITra8_imxCk2kqUV2GE8oBsf1BIuNDeVeyg44gMhlVPQ?e=nbWrJJ', 'nan', 'nan', '13'),
('2023.0', 'Brightdrop', 'Zevo 600', 'nan', 'AHL', 'Pending', 'nan', 'AHL', 'nan', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('2023.0', 'Brightdrop', 'Zevo 600', 'Parking Assist', 'APA', 'No Calibration Required', 'nan', 'APA', 'P&P', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EVsd6H2mRIhOpy5aojr6EY0BXLiVdx4TWiZ-YwdxNmz_DQ?e=kPOAAM', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '1, 5, 6, 7, 11, 12'),
('2023.0', 'Brightdrop', 'Zevo 600', 'Side Obstacle Detection', 'BSW %', 'On Board Calibration - Blind Spot Warning', 'nan', 'BSW (1)', 'PMI', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '5, 6, 7'),
('2023.0', 'Brightdrop', 'Zevo 600', 'Rear Vision Camera', 'BUC', 'On Board Calibration - Backup Camera', 'nan', 'BUC', 'PMI', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EfefP2ZOjNJIiH-tn5GLCtQBdwstxCeA_w3SHLXHk1pp8A?e=IezRQs', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '6'),
('2023.0', 'Brightdrop', 'Zevo 600', 'Lane Departure Warning', 'LKA %', 'Dynamic Calibration - Lane Keep Assist', 'Dynamic Calibration - Lane Keep Assist', 'LKA (1)', 'Dynamic', 'No pre-qualifications required.', 'No pre-quals', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EbvZraj7_PBFmAO5Vy8hl2YBdj7g7Fuh3R9aNHrC0g0tuA?e=0wLnNM', 'nan', 'nan', 'nan', 'The use of Aftermarket or non-Genuine parts and accessories in ADAS sensor areas including but not limited to the front bumper, front grill, below the front grill, license plate covers, headlamps, windshield, front and rear side panels, mirrors, rear camera lens, and rear bumper area is not recommended due to the potential for degradation of ADAS feature functionality.', 'https://calibercollision.sharepoint.com/:b:/g/enterpriseprojects/VehicleServiceInformation/EcITra8_imxCk2kqUV2GE8oBsf1BIuNDeVeyg44gMhlVPQ?e=nbWrJJ', 'nan', 'nan', '13'),
('2023.0', 'Brightdrop', 'Zevo 600', 'nan', 'NV', 'No Calibration Required', 'nan', 'NV', 'nan', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('2023.0', 'Brightdrop', 'Zevo 600', 'nan', 'SVC', 'No Calibration Required', 'nan', 'SVC', 'nan', 'No pre-qualifications required.', 'No pre-quals', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo400 (ACC 2).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EePd2BZq86pOqKxx8MeDzjoBpx9acE71ehnVI3HYW32SiQ?e=KYBbwO', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo400 (AEB 3).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EVyYoTfPqA1Gkoub2VamHBUBaqUqXuVituobOkWZussRBw?e=QEZ3pf', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo400 (APA 1).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EadKDHQ_nwBOsbLkBYk1jXIBEKsM-l8dgHLah5uRZlNeCQ?e=0q1btK', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo400 (BUC).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/ESW__qbdmp5EnQJKuH5aEEkBn-xZb14R2jkD1gp4Knrvow?e=MgRPsl', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo400 (LKA 1).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EbWqVOfRJr1GudD3td5OENgBrXsgYu_F2M1ld_Zrf1DgMg?e=omqMzR', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo400 (SVC 1).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EYQjFI0AT7RGm7i_iq1WLz4BUvUpcHzC1WpjhwcFQgqsoQ?e=X7KRWm', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo600 (ACC 2).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EeflHwlhxpJDp-Eaj9h2JBYBC6niJU8ahFOz6g9qUS1BFw?e=zyqFGu', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo600 (AEB 3).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EUT4uw0OnDJJspdqXvivnMQBcGkLWdLr27upbrB2xEFnjA?e=6q1Auy', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo600 (APA 1).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EZjvZ9RG1SNJh9-MPZ61OmoBHOm9wnbOEW9zA0LdT31GfA?e=tbxJOa', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo600 (BUC).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EQao6MFV8tBNt-SzoG6phlABzlNB9xcXNCPMMinzIUO1_g?e=czd02s', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo600 (LKA 1).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EbarDFiDyTRCtGoA2dHyDKEBkTJmq4_zbysnbyNXFxj7-g?e=9yVbLz', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'),
('nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', '2024 Brightdrop Zevo600 (SVC 1).pdf', 'https://calibercollision.sharepoint.com/:b:/s/O365-Protech-InformationSolutions/EXii9fPFKi5Lr1cZ2B7Lj-wBvc-Cb-i1q_GJR6qhM4rQFA?e=v3eAMp', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
COMMIT;

